### ISSUE TITLE
output with shape [512] doesn't match the broadcast shape [1, 512, 1, 512]

### ISSUE THREAD

**Issue by aakshroy20** [christiansafka/img2vec#13]
Hi I was using your get vector function to extract features of MSCOCO images and I am getting the above error .
Can you please help me I dont understand why is this happening. 
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-28-0bceb69eaeca> in <module>
      1 image=[]
      2 for path in new_df['filename']:
----> 3     img=get_vector(path)
      4     image.append(img)

<ipython-input-27-a45affe9d8f7> in get_vector(image_name)
     13     h = layer.register_forward_hook(copy_data)
     14     # 6. Run the model on our transformed image
---> 15     model(t_img)
     16     # 7. Detach our copy function from the layer
     17     h.remove()

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    548             result = self._slow_forward(*input, **kwargs)
    549         else:
--> 550             result = self.forward(*input, **kwargs)
    551         for hook in self._forward_hooks.values():
    552             hook_result = hook(self, input, result)

/opt/conda/lib/python3.7/site-packages/torchvision/models/resnet.py in forward(self, x)
    218 
    219     def forward(self, x):
--> 220         return self._forward_impl(x)
    221 
    222 

/opt/conda/lib/python3.7/site-packages/torchvision/models/resnet.py in _forward_impl(self, x)
    211         x = self.layer4(x)
    212 
--> 213         x = self.avgpool(x)
    214         x = torch.flatten(x, 1)
    215         x = self.fc(x)

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    550             result = self.forward(*input, **kwargs)
    551         for hook in self._forward_hooks.values():
--> 552             hook_result = hook(self, input, result)
    553             if hook_result is not None:
    554                 result = hook_result

<ipython-input-27-a45affe9d8f7> in copy_data(m, i, o)
      9     # 4. Define a function that will copy the output of a layer
     10     def copy_data(m, i, o):
---> 11         my_embedding.copy_(o.data)
     12     # 5. Attach that function to our selected layer
     13     h = layer.register_forward_hook(copy_data)

RuntimeError: output with shape [512] doesn't match the broadcast shape [1, 512, 1, 512]

**Comment by christiansafka** [comment]
Hi, were you able to solve this?  I'm not getting any errors when I pull the latest version of img2vec and PyTorch.
