### ISSUE TITLE
torchvision 0.9.0 waring

### ISSUE THREAD

**Issue by wind2008hxy** [christiansafka/img2vec#26]
transforms.py:286: UserWarning: The use of the transforms.Scale transform is deprecated, please use transforms.Resize instead.
  "please use transforms.Resize instead.")

**Comment by christiansafka** [comment]
Please make sure you have the latest version of img2vec

**Comment by wind2008hxy** [comment]
> Please make sure you have the latest version of img2vec

thank you, it work
