### ISSUE TITLE
RGBA images convert

### ISSUE THREAD

**Issue by Futurne** [christiansafka/img2vec#28]
Hi,
I used your library and got a problem with my images because the PIL channels were 'RGBA' instead of 'RGB'. It is not a big deal since it is possible to convert using the `img.convert('RGB')` function.
I just thought you could add a comment somewhere that the model needs RGB image, or you could try to convert the input image yourself in the get_vec function ?

Have a good day !
Pierrot

**Comment by christiansafka** [comment]
Added a small comment in readme, thanks.
