### ISSUE TITLE
How can I create image embeddings of size 256?

### ISSUE THREAD

**Issue by monajalal** [christiansafka/img2vec#36]
Thanks for your great work. I noticed that smallest image embedding pertains to ResNet18 which is 512. Do you have any suggestion for a proper model that could lead to feature size of 256?

**Comment by christiansafka** [comment]
I recently used this efficientNet autoencoder for a different project:  https://github.com/lukemelas/EfficientNet-PyTorch/pull/257/

The vector length was around 218.  Would consider adding that to this repo when I find the time.

If you need exactly 256 you could also try dimensionality reduction on the 512 vector.  For example use PCA to reduce from 512 -> 256.

**Comment by frutik** [comment]
```
from sklearn.decomposition import PCA

pca = PCA(n_components=256)
vector_256d = pca.fit_transform(list_of_all_your_vectors_512d)
```
