### ISSUE TITLE
OrderedDict mutated during iteration

### ISSUE THREAD

**Issue by HenryBao91** [christiansafka/img2vec#40]
I occured with an error :
 ```
  img = Image.open('xxx.jpg')
  embddeing = img2vec.get_vec(img=img)
```
I got the error `OrderedDict mutated during iteration`. Not all the time,  it's seldom. I read the source code and I don't find any answer about this error.

**Comment by yinxiangshi** [comment]
Use the debugger to find the wrong ops for dict and use .copy() to avoid OrderedDict mutated during iteration, don't just report what error, report the exact all error info plz
