### ISSUE TITLE
Reduce dimension

### ISSUE THREAD

**Issue by Kencho5** [christiansafka/img2vec#41]
hello,

is there any way i can use other model and layer to output vectors with 128 dimensions instead of 512, which is the smallest one in img2vec. or maybe there is a way to reduce it to 128 dimensions?

**Comment by christiansafka** [comment]
Hi, you could look into some dimensionality reduction techniques such as PCA to reduce the 512 further to 128.  Alternatively you could try adding a new model to img2vec that suits your needs, but there's no guide for that.  If you do decide to try that, maybe the blog post on how I built img2vec will be useful:  https://becominghuman.ai/extract-a-feature-vector-for-any-image-with-pytorch-9717561d1d4c
