### ISSUE TITLE
using img2vec for a resnet18 trained on specific images that has a pytorch lightning ckpt

### ISSUE THREAD

**Issue by monajalal** [christiansafka/img2vec#42]
Hi Christian,

I am wondering if there would be a chance to use the following script but use the ckpt from https://github.com/ozanciga/self-supervised-histopathology/releases/tag/tenpercent  ( [tenpercent_resnet18.ckpt](https://github.com/ozanciga/self-supervised-histopathology/releases/download/tenpercent/tenpercent_resnet18.ckpt) )

```
from img2vec_pytorch import Img2Vec
from PIL import Image
import torch
import glob
import os

# # Initialize Img2Vec with GPU
img2vec = Img2Vec(cuda=True)
counter = 0 
for dirpath, dirname, filename in os.walk('resnet18_patches'):
    if dirpath.endswith('20.0'):
        images_full_path = dirpath + '/*.jpeg'
        for img in glob.glob(images_full_path):
            rgb_img = Image.open(img)
            vec = img2vec.get_vec(rgb_img, tensor=True)
            vec_name = os.path.basename(img)[:-5] + '.pt'
            dir_name = os.path.dirname(img) 
            torch.save(vec, dir_name + '/' + vec_name)
        counter += 1
        print('finished {} directories'.format(counter))

```

https://github.com/ozanciga/self-supervised-histopathology/issues/8

**Comment by christiansafka** [comment]
Hi, I haven't planned to add this but it's possible to do it yourself.  You'll need to modify the part of img2vec code where the resnet model is loaded and replace that with loading directly from that checkpoint file.  Here there are some examples:
https://pytorch.org/tutorials/beginner/saving_loading_models.html

**Comment by christiansafka** [comment]
Or to go a step further, it's possible to add a new parameter to Img2vec that accepts a model checkpoint for the existing models in the project.  That could be a useful addition to this project.
