### ISSUE TITLE
Cuda Performance Question

### ISSUE THREAD

**Issue by selected-pixel-jameson** [christiansafka/img2vec#46]
Hello,

First off, thank you for this library! It's awesome!

This is a general question and not an issue. 

I'm implementing this library like so to test the timing.

```
tic = time.perf_counter()

toc = time.perf_counter()
print(f"Step Zero {toc - tic:0.4f} seconds")
img2vec = Img2Vec(cuda=False, model="resnet18", layer_output_size=512)

toc = time.perf_counter()
print(f"Step One {toc - tic:0.4f} seconds")

img = Image.open(requests.get(request.url, stream=True).raw).convert("RGB")
toc = time.perf_counter()
print(f"Step Two {toc - tic:0.4f} seconds")

vector = img2vec.get_vec(img, tensor=False)
print(f"Step Three {toc - tic:0.4f} seconds")

```

This outputs.

```
Step Zero 0.0000 seconds
Step One 0.2044 seconds
Step Two 0.5028 seconds
Step Three 0.5361 seconds
```

If I were to run this with cuda=True would I see the performance improvement at Step One? If so, what could I general expect for a performance increase? 

Thanks again.

**Comment by christiansafka** [comment]
Hi there - I'd expect Step One to actually take a bit longer with Cuda enabled as it would have to initalize Cuda.  The performance increase would be at Step Three where the inference is being run.  I'm not sure of the exact numbers but it should be a significant improvement if you plan to generate vectors for many images.

**Comment by selected-pixel-jameson** [comment]
@christiansafka That's interesting considering that part is only taking ~ 30ms [535ms - 502ms]... Was hoping enabling CUDA would take the initial step down thus reducing the request by 100 - 200ms. My main concern is getting a single response to return under 500ms right now.

**Comment by christiansafka** [comment]
That initalization only needs to happen one time, not per request.  If your use case applies you should only be loading the Img2vec once and then run get_vec per request

**Comment by selected-pixel-jameson** [comment]
@christiansafka I literally just realized this! Wow. Thank you!
