### ISSUE TITLE
Best Model for High Accuracy When Performing CosineSimilarity Search

### ISSUE THREAD

**Issue by selected-pixel-jameson** [christiansafka/img2vec#47]
Hello,

I'm wonder which model is the best to use when trying to find the most accurate images, regardless of performance, when performing a CosineSimilarity Search?  My goal is to find the same image, but with very slight differences, i.e. a smudge or slight glare. 

Thank you.

**Comment by christiansafka** [comment]
Hi, you can look up the accuracy for all the models but I think what you're looking for is robustness.  Try the model with the smallest feature vector length - the intuition being that more compression is more robust to minor changes in the image.  The vector should be similar with or without a smudge.
