### ISSUE TITLE
Question: Should I resize my images?

### ISSUE THREAD

**Issue by selected-pixel-jameson** [christiansafka/img2vec#48]
I'm just wondering if I should be resizing the provided image to the Resnet expected size? 

For example Resnet50 is expecting 224x224 image sizes. Or is that taken care of?

**Comment by christiansafka** [comment]
Looks like there's an existing transform for resizing, so it's taken care of.  You may consider cropping your images to equal width and height though - to avoid any distortion.
https://github.com/christiansafka/img2vec/blob/8b63ed677327382b5db56dc9b193ca32fd3a8b9f/img2vec_pytorch/img_to_vec.py#L44

**Comment by selected-pixel-jameson** [comment]
Thank you!
