### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by GertjanBrouwer** [christiansafka/img2vec#5]
Hi, 

I get this error on this piece of code:
`def copy_data(m, i, o):
            my_embedding.copy_(o.data)`

`RuntimeError
  Message=expand(torch.FloatTensor{[1, 512, 1, 1]}, size=[512]): the number of sizes provided (1) must be greater or equal to the number of dimensions in the tensor (4)
`

I am running pytorch-cpu 0.4.0-py36_cpuhe774522_1

**Comment by ecm2113** [comment]
Yes, I have the same error.  Can you advise?

**Comment by GertjanBrouwer** [comment]
I changed this line:
`my_embedding = torch.zeros(512)`
to this:
`my_embedding = torch.zeros(1, 512, 1, 1)`

And this: 
`vec = img2vec.get_vec(img)`
to this:
`vec = img2vec.get_vec(img)
vec = vec.view(512)`

Where 512 is the output of resnet fully connected layer. 

I don't know exactly why it does work and I don't have time to find out. But this is a working solution for now

**Comment by valavanisleonidas** [comment]
Same error here. The workaround of the comment above works?

**Comment by christiansafka** [comment]
Thanks for the temp solution @GertjanBrouwer, I've merged a fix for this.
