### ISSUE TITLE
alexnet tensor size error

### ISSUE THREAD

**Issue by adamhrv** [christiansafka/img2vec#7]
Current, using `alexnet` throws the error `The expanded size of the tensor (1) must match the existing size (4096) at non-singleton dimension 3` resulting from the previous update `my_embedding = torch.zeros(1, self.layer_output_size, 1, 1)` 

Patch for using alexnet:
1) Change `my_embedding = torch.zeros(1, self.layer_output_size, 1, 1)` to `my_embedding = torch.zeros(1, self.layer_output_size)` if using alexnet
2) Change `tensor = my_embedding.numpy()[0, :, 1, 1]` to `tensor = my_embedding.numpy()[0, :]`

Thanks for making this. Look forward to pip installable version.

**Comment by christiansafka** [comment]
Thanks Adam, patched it
